### ISSUE TITLE
zj老师你好,求16节课的新版jeb🤩🤩🤩

### ISSUE THREAD

**Issue by BingQianceng** [ZJ595/AndroidReverse#5]
找了半天没找到,有的页面404了

**Comment by ZJ595** [comment]
> 找了半天没找到,有的页面404了

课件里我记得有，不然你就看看这个
[转帖]JEB Decompiler 5.16.0.20240826fix1745 mod by CXV()
https://www.52pojie.cn/thread-1958266-1-1.html
